import argparse
import json
import re
import codecs
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _extract_dataset_from_html(html: str):
    m = re.search(r"const dataset = (\[.*?\]);", html, flags=re.S)
    if not m:
        raise ValueError("dataset block not found in source html")
    payload = m.group(1)
    try:
        return json.loads(payload)
    except json.JSONDecodeError:
        # Standalone html may contain escaped JSON payload inside JS string.
        unpacked = codecs.decode(payload, "unicode_escape")
        return json.loads(unpacked)


def _write_dataset_php(dataset, out_path: Path):
    json_text = json.dumps(dataset, ensure_ascii=False, separators=(",", ":"))
    php = (
        "<?php\n"
        "// Auto-generated by scripts/generate_gnuboard_blackbox_package.py\n"
        "$json = <<<'JSON'\n"
        f"{json_text}\n"
        "JSON;\n"
        "$rows = json_decode($json, true);\n"
        "if (!is_array($rows)) { $rows = array(); }\n"
        "return $rows;\n"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(php, encoding="utf-8")


def _write_api_php(dataset_rel_path: str, out_path: Path):
    php = f"""<?php
// Auto-generated by scripts/generate_gnuboard_blackbox_package.py
// 목적: 그누보드5 환경에서 데이터셋을 브라우저에 노출하지 않고 서버에서 양도가 산정.

header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {{
    http_response_code(405);
    echo json_encode(array('ok' => false, 'error' => 'POST only'), JSON_UNESCAPED_UNICODE);
    exit;
}}

$raw = file_get_contents('php://input');
$input = json_decode($raw, true);
if (!is_array($input)) {{
    http_response_code(400);
    echo json_encode(array('ok' => false, 'error' => 'invalid json'), JSON_UNESCAPED_UNICODE);
    exit;
}}

$dataset = require __DIR__ . '/{dataset_rel_path}';
if (!is_array($dataset) || !count($dataset)) {{
    http_response_code(500);
    echo json_encode(array('ok' => false, 'error' => 'dataset unavailable'), JSON_UNESCAPED_UNICODE);
    exit;
}}

function num_or_null($v) {{
    if ($v === null || $v === '') return null;
    if (is_string($v)) {{
        $v = str_replace(',', '', trim($v));
    }}
    if (!is_numeric($v)) return null;
    return floatval($v);
}}

function s_trim($v) {{
    if ($v === null) return '';
    return trim((string)$v);
}}

function normalize_token($t) {{
    $x = preg_replace('/\\s+/u', '', s_trim($t));
    $x = str_replace(array('(주)','주식회사','공사업','건설업','공사','사업','업종','면허'), '', $x);
    return $x;
}}

function tokenize_license($raw) {{
    $txt = str_replace(array("<br>","<br/>","<br />"), "\\n", s_trim($raw));
    $parts = preg_split('/[\\n\\/,|·ㆍ+&\\s]+/u', $txt);
    $out = array();
    foreach ($parts as $p) {{
        $n = normalize_token($p);
        if ($n !== '') $out[$n] = true;
    }}
    return array_keys($out);
}}

function set_intersection_count($a, $b) {{
    $map = array();
    foreach ($a as $x) {{ $map[$x] = true; }}
    $cnt = 0;
    foreach ($b as $x) {{
        if (isset($map[$x])) $cnt++;
    }}
    return $cnt;
}}

function jaccard($a, $b) {{
    if (!count($a) || !count($b)) return 0.0;
    $inter = set_intersection_count($a, $b);
    $union = count(array_unique(array_merge($a, $b)));
    if ($union <= 0) return 0.0;
    return $inter / $union;
}}

function rel_close($x, $y) {{
    if ($x === null || $y === null) return 0.35;
    $d = max(abs($x), abs($y), 1.0);
    $r = abs($x - $y) / $d;
    return max(0.0, 1.0 - min(1.0, $r));
}}

function weighted_quantile($vals, $weights, $q) {{
    $arr = array();
    for ($i = 0; $i < count($vals); $i++) {{
        $v = $vals[$i];
        $w = $weights[$i];
        if (!is_numeric($v) || !is_numeric($w) || $w <= 0) continue;
        $arr[] = array(floatval($v), floatval($w));
    }}
    if (!count($arr)) return null;
    usort($arr, function($a, $b) {{
        if ($a[0] == $b[0]) return 0;
        return ($a[0] < $b[0]) ? -1 : 1;
    }});
    $total = 0.0;
    foreach ($arr as $p) {{ $total += $p[1]; }}
    if ($total <= 0) return null;
    $target = min(max($q, 0.0), 1.0) * $total;
    $run = 0.0;
    foreach ($arr as $p) {{
        $run += $p[1];
        if ($run >= $target) return $p[0];
    }}
    return $arr[count($arr) - 1][0];
}}

function top_neighbors($target, $dataset, $k = 12) {{
    $scored = array();
    foreach ($dataset as $row) {{
        $candTokens = array();
        if (isset($row['tokens']) && is_array($row['tokens'])) {{
            foreach ($row['tokens'] as $t) {{
                $candTokens[] = normalize_token($t);
            }}
        }} else {{
            $candTokens = tokenize_license(isset($row['license_text']) ? $row['license_text'] : '');
        }}
        $interCnt = set_intersection_count($target['tokens'], $candTokens);
        $score = 0.0;
        $score += jaccard($target['tokens'], $candTokens) * 50.0;
        $score += min(15.0, 4.0 * $interCnt);
        $score += rel_close($target['specialty'], num_or_null($row['specialty'])) * 6.0;
        $score += rel_close($target['focus_sales'], max(num_or_null($row['sales3_eok']), num_or_null($row['sales5_eok']))) * 8.0;
        $score += rel_close($target['license_year'], num_or_null($row['license_year'])) * 2.0;
        $score += rel_close($target['balance_eok'], num_or_null($row['balance_eok'])) * 12.0;
        $score += rel_close($target['capital_eok'], num_or_null($row['capital_eok'])) * 10.0;
        $score += rel_close($target['surplus_risk'], num_or_null($row['surplus_eok'])) * 10.0;

        if (count($target['tokens']) && count($candTokens) && $interCnt === 0) {{
            $score *= 0.55;
        }}
        $score = max(0.0, min(100.0, $score));
        if ($score <= 0.01) continue;
        $scored[] = array($score, $row);
    }}
    usort($scored, function($a, $b) {{
        if ($a[0] == $b[0]) return 0;
        return ($a[0] > $b[0]) ? -1 : 1;
    }});
    return array_slice($scored, 0, $k);
}}

$license = s_trim(isset($input['license_text']) ? $input['license_text'] : (isset($input['license']) ? $input['license'] : ''));
$tokens = tokenize_license($license);
$y23 = num_or_null(isset($input['y23']) ? $input['y23'] : (isset($input['y23_eok']) ? $input['y23_eok'] : null));
$y24 = num_or_null(isset($input['y24']) ? $input['y24'] : (isset($input['y24_eok']) ? $input['y24_eok'] : null));
$y25 = num_or_null(isset($input['y25']) ? $input['y25'] : (isset($input['y25_eok']) ? $input['y25_eok'] : null));
$y22 = num_or_null(isset($input['y22']) ? $input['y22'] : (isset($input['y22_eok']) ? $input['y22_eok'] : null));
$y21 = num_or_null(isset($input['y21']) ? $input['y21'] : (isset($input['y21_eok']) ? $input['y21_eok'] : null));

$sales3 = 0.0;
$cnt3 = 0;
foreach (array($y23, $y24, $y25) as $v) {{
    if ($v !== null) {{ $sales3 += $v; $cnt3++; }}
}}
$sales3 = ($cnt3 > 0) ? $sales3 : null;

$sales5 = 0.0;
$cnt5 = 0;
foreach (array($y21, $y22, $y23, $y24, $y25) as $v) {{
    if ($v !== null) {{ $sales5 += $v; $cnt5++; }}
}}
$sales5 = ($cnt5 > 0) ? $sales5 : $sales3;
$focusSales = max($sales3 !== null ? $sales3 : 0.0, $sales5 !== null ? $sales5 : 0.0);
$salesPoint = ($sales3 !== null && $sales5 !== null && $sales3 >= $sales5)
    ? '최근 실적 상승세 (3년 실적 우수)'
    : '장기 안정성 (5년 실적 우수)';

$target = array(
    'tokens' => $tokens,
    'license_year' => num_or_null(isset($input['license_year']) ? $input['license_year'] : null),
    'specialty' => num_or_null(isset($input['specialty']) ? $input['specialty'] : null),
    'balance_eok' => num_or_null(isset($input['balance_eok']) ? $input['balance_eok'] : (isset($input['balance']) ? $input['balance'] : null)),
    'capital_eok' => num_or_null(isset($input['capital_eok']) ? $input['capital_eok'] : (isset($input['capital']) ? $input['capital'] : null)),
    // 이익잉여금은 높을수록 매수자 입장 관리 리스크로 반영(감산 요소)
    'surplus_risk' => num_or_null(isset($input['surplus_eok']) ? $input['surplus_eok'] : (isset($input['surplus']) ? $input['surplus'] : null)),
    'sales3' => $sales3,
    'sales5' => $sales5,
    'focus_sales' => $focusSales,
);

$neighbors = top_neighbors($target, $dataset, 12);
if (!count($neighbors)) {{
    echo json_encode(array(
        'ok' => true,
        'center' => null,
        'low' => null,
        'high' => null,
        'confidence_score' => 0,
        'confidence' => '0%',
        'risk_notes' => array('입력 항목이 부족하여 산정 가능한 유사 매물을 찾지 못했습니다.'),
        'neighbors' => array(),
        'sales_point' => $salesPoint,
    ), JSON_UNESCAPED_UNICODE);
    exit;
}}

$prices = array();
$weights = array();
foreach ($neighbors as $pair) {{
    $sim = floatval($pair[0]);
    $row = $pair[1];
    $p = num_or_null(isset($row['price_eok']) ? $row['price_eok'] : null);
    if ($p === null || $p <= 0) continue;
    $prices[] = $p;
    $weights[] = max(0.1, $sim);
}}

$center = weighted_quantile($prices, $weights, 0.5);
$low = weighted_quantile($prices, $weights, 0.25);
$high = weighted_quantile($prices, $weights, 0.75);
if ($center === null) $center = (count($prices) ? array_sum($prices) / count($prices) : null);
if ($low === null) $low = $center;
if ($high === null) $high = $center;
if ($low !== null && $high !== null && $low > $high) {{
    $tmp = $low; $low = $high; $high = $tmp;
}}

$avgSim = 0.0;
foreach ($neighbors as $pair) {{ $avgSim += floatval($pair[0]); }}
$avgSim = $avgSim / max(1, count($neighbors));
$confidence = max(0.0, min(100.0, ($avgSim * 0.62) + min(24.0, count($neighbors) * 2.8)));

$riskNotes = array();
if ($target['balance_eok'] === null) $riskNotes[] = '공제조합 잔액 미입력: 오차가 커질 수 있습니다.';
if ($target['capital_eok'] === null) $riskNotes[] = '자본금 미입력: 기업가치 보정이 제한됩니다.';
if ($target['surplus_risk'] === null) $riskNotes[] = '이익잉여금 미입력: 인수 리스크 반영이 제한됩니다.';
if (!count($tokens)) $riskNotes[] = '면허/업종 미입력: 유사 매칭 정확도가 낮아집니다.';
if (!count($riskNotes)) $riskNotes[] = '핵심 항목 입력이 양호합니다.';
$riskNotes[] = $salesPoint;

$neighborOut = array();
foreach ($neighbors as $pair) {{
    $sim = round(floatval($pair[0]), 1);
    $row = $pair[1];
    $neighborOut[] = array(
        'similarity' => $sim,
        'seoul_no' => isset($row['seoul_no']) ? intval($row['seoul_no']) : 0,
        'license_text' => isset($row['license_text']) ? (string)$row['license_text'] : '',
        'price_eok' => num_or_null(isset($row['price_eok']) ? $row['price_eok'] : null),
        'display_low_eok' => num_or_null(isset($row['display_low_eok']) ? $row['display_low_eok'] : null),
        'display_high_eok' => num_or_null(isset($row['display_high_eok']) ? $row['display_high_eok'] : null),
        'url' => isset($row['url']) ? (string)$row['url'] : '',
    );
}}

echo json_encode(array(
    'ok' => true,
    'center' => ($center !== null ? round($center, 4) : null),
    'low' => ($low !== null ? round($low, 4) : null),
    'high' => ($high !== null ? round($high, 4) : null),
    'confidence_score' => round($confidence, 1),
    'confidence' => round($confidence) . '%',
    'risk_notes' => $riskNotes,
    'neighbors' => $neighborOut,
    'sales_point' => $salesPoint,
), JSON_UNESCAPED_UNICODE);
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(php, encoding="utf-8")


def _write_readme(dataset_count: int, out_path: Path):
    md = f"""# 그누보드5 블랙박스 배포 패키지

생성 시각: 자동 생성
데이터셋 건수: {dataset_count}

## 포함 파일
- `api_calc.php`: 서버측 산정 API (POST JSON)
- `yangdo_dataset.php`: 서버측 학습 데이터셋 (PHP include)

## 배포 위치 권장
- `api_calc.php` → `seoulmna.co.kr` 웹루트
- `yangdo_dataset.php` → 웹루트 하위 `include/` 또는 외부 비공개 경로

## 보안 권장
- `api_calc.php`는 same-origin만 허용하도록 도메인 체크 추가 가능
- 요청 빈도 제한(예: 분당 60회/IP)을 서버 레벨로 추가
- `yangdo_dataset.php`는 직접 URL 접근 차단(.htaccess / nginx location deny)

## 프론트엔드 연결
- `.env`에 `YANGDO_ESTIMATE_ENDPOINT=https://seoulmna.co.kr/api_calc.php` 설정
- `py -3 scripts/deploy_yangdo_site_release.py --publish` 재실행 시 브라우저에서 원본 dataset 미노출 모드 동작
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Generate gnuboard5 blackbox package (api_calc.php + dataset php)")
    parser.add_argument(
        "--source-html",
        default="output/yangdo_price_calculator_owner_standalone.html",
        help="HTML file that contains const dataset = [...]",
    )
    parser.add_argument("--out-dir", default="output/deploy/gnuboard_blackbox")
    args = parser.parse_args()

    src = (ROOT / args.source_html).resolve()
    if not src.exists():
        raise FileNotFoundError(f"source html not found: {src}")
    html = src.read_text(encoding="utf-8", errors="replace")
    dataset = _extract_dataset_from_html(html)
    out_dir = (ROOT / args.out_dir).resolve()
    dataset_path = out_dir / "yangdo_dataset.php"
    api_path = out_dir / "api_calc.php"
    readme = out_dir / "README.md"

    _write_dataset_php(dataset, dataset_path)
    _write_api_php("yangdo_dataset.php", api_path)
    _write_readme(len(dataset), readme)

    print(f"[ok] generated package in {out_dir}")
    print(f"[dataset_rows] {len(dataset)}")
    print(f"[api] {api_path}")
    print(f"[dataset] {dataset_path}")
    print(f"[readme] {readme}")


if __name__ == "__main__":
    main()
